naam = input('naam: ')
adres = input('adres: ')
postcode = input('postcode: ')
woonplaats = input('woonplaats: ')
print ('------------------------------------')
print('naam: ' + naam)
print('adres:' + adres)
print('postcode' + postcode)
print('woonplaats:' + woonplaats)
print('------------------------------------')